//
// BrokerAccountType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BrokerAccountType: String, Codable, CaseIterable {
    case tinkoff = "Tinkoff"
    case tinkoffIis = "TinkoffIis"
}
