//
// CandlesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CandlesResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: Candles

    public init(trackingId: String, status: String = "Ok", payload: Candles) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
