//
// Candle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Candle: Codable {

    public var figi: String
    public var interval: CandleResolution
    public var o: Double
    public var c: Double
    public var h: Double
    public var l: Double
    public var v: Int
    /** ISO8601 */
    public var time: Date

    public init(figi: String, interval: CandleResolution, o: Double, c: Double, h: Double, l: Double, v: Int, time: Date) {
        self.figi = figi
        self.interval = interval
        self.o = o
        self.c = c
        self.h = h
        self.l = l
        self.v = v
        self.time = time
    }

}
