//
// Candles.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Candles: Codable {

    public var figi: String
    public var interval: CandleResolution
    public var candles: [Candle]

    public init(figi: String, interval: CandleResolution, candles: [Candle]) {
        self.figi = figi
        self.interval = interval
        self.candles = candles
    }

}
