//
// CandleResolution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Интервал свечи и допустимый промежуток запроса: - 1min [1 minute, 1 day] - 2min [2 minutes, 1 day] - 3min [3 minutes, 1 day] - 5min [5 minutes, 1 day] - 10min [10 minutes, 1 day] - 15min [15 minutes, 1 day] - 30min [30 minutes, 1 day] - hour [1 hour, 7 days] - day [1 day, 1 year] - week [7 days, 2 years] - month [1 month, 10 years]  */
public enum CandleResolution: String, Codable, CaseIterable {
    case _1min = "1min"
    case _2min = "2min"
    case _3min = "3min"
    case _5min = "5min"
    case _10min = "10min"
    case _15min = "15min"
    case _30min = "30min"
    case hour = "hour"
    case day = "day"
    case week = "week"
    case month = "month"
}
