//
// Currencies.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Currencies: Codable {

    public var currencies: [CurrencyPosition]

    public init(currencies: [CurrencyPosition]) {
        self.currencies = currencies
    }

}
