//
// Currency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum Currency: String, Codable, CaseIterable {
    case rub = "RUB"
    case usd = "USD"
    case eur = "EUR"
    case gbp = "GBP"
    case hkd = "HKD"
    case chf = "CHF"
    case jpy = "JPY"
    case cny = "CNY"
    case _try = "TRY"
}
