//
// CurrencyPosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CurrencyPosition: Codable {

    public var currency: Currency
    public var balance: Double
    public var blocked: Double?

    public init(currency: Currency, balance: Double, blocked: Double? = nil) {
        self.currency = currency
        self.balance = balance
        self.blocked = blocked
    }

}
