//
// Empty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Empty: Codable {

    public var trackingId: String
    public var payload: Any
    public var status: String = "Ok"

    public init(trackingId: String, payload: Any, status: String = "Ok") {
        self.trackingId = trackingId
        self.payload = payload
        self.status = status
    }

}
