//
// ErrorPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ErrorPayload: Codable {

    public var message: String?
    public var code: String?

    public init(message: String? = nil, code: String? = nil) {
        self.message = message
        self.code = code
    }

}
