//
// InstrumentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum InstrumentType: String, Codable, CaseIterable {
    case stock = "Stock"
    case currency = "Currency"
    case bond = "Bond"
    case etf = "Etf"
}
