//
// LimitOrderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LimitOrderRequest: Codable {

    public var lots: Int
    public var operation: OperationType
    public var price: Double

    public init(lots: Int, operation: OperationType, price: Double) {
        self.lots = lots
        self.operation = operation
        self.price = price
    }

}
