//
// LimitOrderResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LimitOrderResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: PlacedLimitOrder

    public init(trackingId: String, status: String = "Ok", payload: PlacedLimitOrder) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
