//
// MarketInstrumentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MarketInstrumentResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: MarketInstrument

    public init(trackingId: String, status: String = "Ok", payload: MarketInstrument) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
