//
// MarketOrderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MarketOrderRequest: Codable {

    public var lots: Int
    public var operation: OperationType

    public init(lots: Int, operation: OperationType) {
        self.lots = lots
        self.operation = operation
    }

}
