//
// MarketInstrumentListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MarketInstrumentListResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: MarketInstrumentList

    public init(trackingId: String, status: String = "Ok", payload: MarketInstrumentList) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
