//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModelError: Codable {

    public var trackingId: String
    public var status: String = "Error"
    public var payload: ErrorPayload

    public init(trackingId: String, status: String = "Error", payload: ErrorPayload) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
