//
// MoneyAmount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MoneyAmount: Codable {

    public var currency: Currency
    public var value: Double

    public init(currency: Currency, value: Double) {
        self.currency = currency
        self.value = value
    }

}
