//
// OperationStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Статус заявки */
public enum OperationStatus: String, Codable, CaseIterable {
    case done = "Done"
    case decline = "Decline"
    case progress = "Progress"
}
