//
// OperationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OperationType: String, Codable, CaseIterable {
    case buy = "Buy"
    case sell = "Sell"
}
