//
// OperationTypeWithCommission.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OperationTypeWithCommission: String, Codable, CaseIterable {
    case buy = "Buy"
    case buyCard = "BuyCard"
    case sell = "Sell"
    case brokerCommission = "BrokerCommission"
    case exchangeCommission = "ExchangeCommission"
    case serviceCommission = "ServiceCommission"
    case marginCommission = "MarginCommission"
    case otherCommission = "OtherCommission"
    case payIn = "PayIn"
    case payOut = "PayOut"
    case tax = "Tax"
    case taxLucre = "TaxLucre"
    case taxDividend = "TaxDividend"
    case taxCoupon = "TaxCoupon"
    case taxBack = "TaxBack"
    case repayment = "Repayment"
    case partRepayment = "PartRepayment"
    case coupon = "Coupon"
    case dividend = "Dividend"
    case securityIn = "SecurityIn"
    case securityOut = "SecurityOut"
}
