//
// Operations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Operations: Codable {

    public var operations: [Operation]

    public init(operations: [Operation]) {
        self.operations = operations
    }

}
