//
// Operation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Operation: Codable {

    public var id: String
    public var status: OperationStatus
    public var trades: [OperationTrade]?
    public var commission: MoneyAmount?
    public var currency: Currency
    public var payment: Double
    public var price: Double?
    /** Число инструментов в выставленной заявке */
    public var quantity: Int?
    /** Число инструментов, исполненных в заявке */
    public var quantityExecuted: Int?
    public var figi: String?
    public var instrumentType: InstrumentType?
    public var isMarginCall: Bool
    /** ISO8601 */
    public var date: Date
    public var operationType: OperationTypeWithCommission?

    public init(id: String, status: OperationStatus, trades: [OperationTrade]? = nil, commission: MoneyAmount? = nil, currency: Currency, payment: Double, price: Double? = nil, quantity: Int? = nil, quantityExecuted: Int? = nil, figi: String? = nil, instrumentType: InstrumentType? = nil, isMarginCall: Bool, date: Date, operationType: OperationTypeWithCommission? = nil) {
        self.id = id
        self.status = status
        self.trades = trades
        self.commission = commission
        self.currency = currency
        self.payment = payment
        self.price = price
        self.quantity = quantity
        self.quantityExecuted = quantityExecuted
        self.figi = figi
        self.instrumentType = instrumentType
        self.isMarginCall = isMarginCall
        self.date = date
        self.operationType = operationType
    }

}
