//
// OrderbookResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OrderbookResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: Orderbook

    public init(trackingId: String, status: String = "Ok", payload: Orderbook) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
