//
// Order.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Order: Codable {

    public var orderId: String
    public var figi: String
    public var operation: OperationType
    public var status: OrderStatus
    public var requestedLots: Int
    public var executedLots: Int
    public var type: OrderType
    public var price: Double

    public init(orderId: String, figi: String, operation: OperationType, status: OrderStatus, requestedLots: Int, executedLots: Int, type: OrderType, price: Double) {
        self.orderId = orderId
        self.figi = figi
        self.operation = operation
        self.status = status
        self.requestedLots = requestedLots
        self.executedLots = executedLots
        self.type = type
        self.price = price
    }

}
