//
// OrderType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Тип заявки */
public enum OrderType: String, Codable, CaseIterable {
    case limit = "Limit"
    case market = "Market"
}
