//
// OrdersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OrdersResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: [Order]

    public init(trackingId: String, status: String = "Ok", payload: [Order]) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
