//
// OrderStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Статус заявки */
public enum OrderStatus: String, Codable, CaseIterable {
    case new = "New"
    case partiallyFill = "PartiallyFill"
    case fill = "Fill"
    case cancelled = "Cancelled"
    case replaced = "Replaced"
    case pendingCancel = "PendingCancel"
    case rejected = "Rejected"
    case pendingReplace = "PendingReplace"
    case pendingNew = "PendingNew"
}
