//
// PortfolioResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PortfolioResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: Portfolio

    public init(trackingId: String, status: String = "Ok", payload: Portfolio) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
