//
// Portfolio.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Portfolio: Codable {

    public var positions: [PortfolioPosition]

    public init(positions: [PortfolioPosition]) {
        self.positions = positions
    }

}
