//
// PortfolioCurrenciesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PortfolioCurrenciesResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: Currencies

    public init(trackingId: String, status: String = "Ok", payload: Currencies) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
