//
// SandboxAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SandboxAccount: Codable {

    public var brokerAccountType: BrokerAccountType
    public var brokerAccountId: String

    public init(brokerAccountType: BrokerAccountType, brokerAccountId: String) {
        self.brokerAccountType = brokerAccountType
        self.brokerAccountId = brokerAccountId
    }

}
