//
// SandboxSetCurrencyBalanceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SandboxSetCurrencyBalanceRequest: Codable {

    public var currency: SandboxCurrency
    public var balance: Double

    public init(currency: SandboxCurrency, balance: Double) {
        self.currency = currency
        self.balance = balance
    }

}
