//
// SandboxRegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SandboxRegisterRequest: Codable {

    public var brokerAccountType: BrokerAccountType?

    public init(brokerAccountType: BrokerAccountType? = nil) {
        self.brokerAccountType = brokerAccountType
    }

}
