//
// SandboxRegisterResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SandboxRegisterResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: SandboxAccount

    public init(trackingId: String, status: String = "Ok", payload: SandboxAccount) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
