//
// SearchMarketInstrumentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchMarketInstrumentResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: SearchMarketInstrument

    public init(trackingId: String, status: String = "Ok", payload: SearchMarketInstrument) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
