//
// TradeStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TradeStatus: String, Codable, CaseIterable {
    case normalTrading = "NormalTrading"
    case notAvailableForTrading = "NotAvailableForTrading"
}
