//
// UserAccounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserAccounts: Codable {

    public var accounts: [UserAccount]

    public init(accounts: [UserAccount]) {
        self.accounts = accounts
    }

}
