//
// UserAccountsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserAccountsResponse: Codable {

    public var trackingId: String
    public var status: String = "Ok"
    public var payload: UserAccounts

    public init(trackingId: String, status: String = "Ok", payload: UserAccounts) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }

}
