//
// PortfolioAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PortfolioAPI {
    /**
     Получение валютных активов клиента
     
     - parameter brokerAccountId: (query) Номер счета (по умолчанию - Тинькофф) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func portfolioCurrenciesGet(brokerAccountId: String? = nil, apiResponseQueue: DispatchQueue = TinkoffInvestClientAPI.apiResponseQueue, completion: @escaping ((_ data: PortfolioCurrenciesResponse?, _ error: Error?) -> Void)) {
        portfolioCurrenciesGetWithRequestBuilder(brokerAccountId: brokerAccountId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Получение валютных активов клиента
     - GET /portfolio/currencies
     - BASIC:
       - type: http
       - name: sso_auth
     - parameter brokerAccountId: (query) Номер счета (по умолчанию - Тинькофф) (optional)
     - returns: RequestBuilder<PortfolioCurrenciesResponse> 
     */
    open class func portfolioCurrenciesGetWithRequestBuilder(brokerAccountId: String? = nil) -> RequestBuilder<PortfolioCurrenciesResponse> {
        let path = "/portfolio/currencies"
        let URLString = TinkoffInvestClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "brokerAccountId": brokerAccountId?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<PortfolioCurrenciesResponse>.Type = TinkoffInvestClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Получение портфеля клиента
     
     - parameter brokerAccountId: (query) Номер счета (по умолчанию - Тинькофф) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func portfolioGet(brokerAccountId: String? = nil, apiResponseQueue: DispatchQueue = TinkoffInvestClientAPI.apiResponseQueue, completion: @escaping ((_ data: PortfolioResponse?, _ error: Error?) -> Void)) {
        portfolioGetWithRequestBuilder(brokerAccountId: brokerAccountId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Получение портфеля клиента
     - GET /portfolio
     - BASIC:
       - type: http
       - name: sso_auth
     - parameter brokerAccountId: (query) Номер счета (по умолчанию - Тинькофф) (optional)
     - returns: RequestBuilder<PortfolioResponse> 
     */
    open class func portfolioGetWithRequestBuilder(brokerAccountId: String? = nil) -> RequestBuilder<PortfolioResponse> {
        let path = "/portfolio"
        let URLString = TinkoffInvestClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "brokerAccountId": brokerAccountId?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<PortfolioResponse>.Type = TinkoffInvestClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
